### PR TITLE
Add DevOps roadmap

### LINKED ISSUE #203: [FEATURE] <description>
### Description

Convert the [DevOps roadmap on CC website](https://www.commclassroom.org/devops-roadmap) to a readme.md format in the DevOps folder.

Example:
```
#Frontend Roadmap
## Step one
- Resource 1
- Resource 2
```

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by VishwaS-22**
## Changes proposed

Added resources in a README file for DevOps roadmap .

## Note to reviewers

Hey There! As am working on this issue, half of the work was Completed and the remaining work is have to add Links for several stages once the CC site is available.  
Thank You.

### CODE REVIEW

**Review by siddhant-khisty — APPROVED** [review]
LGTM

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]
- Please complete the PR with resources
- Use md syntax rather than `<h1>`, `<h2>` etc

**Comment by siddhant-khisty** [comment]
Completed by #228

**Comment by VishwaS-22** [comment]
Hey @kaiwalyakoparkar ! Thanks for the feedback. I'll add it soon. 
Thank You! Happy to Contribute.

**Pull request closed without merging**
