### PR TITLE
Update Readme.md

### LINKED ISSUE #218: Adding 2 new Frontend Projects especially for beginners
### Which field of community (DevOps/Opensource/Web/Web3/Android/Devrel) you want to add, drop the links?

Frontend Web Development

### For adding Job Posting, add links here.

_No response_

### For adding OpenSource Projects, add links here.

1. https://github.com/TRohit20/Soldier-Fit-Factory-Website - A responsive website for a gym.
2. https://github.com/TRohit20/Blogs-Website - A responsive Community Driven Blog website

### PR DESCRIPTION
**Pull request by TRohit20**
Added two new Frontend Development projects for anyone to contribute or work on. Happy hacking!!!

## Fixes Issue
Closes #218 

## Changes proposed

Adding two frontend projects which are beginner friendly and responsive.
One is a blogging site which can also be used to work on backend technologies. The other is a landing page for businesses like Gyms

### CODE REVIEW

**Review by siddhant-khisty — APPROVED** [review]
LGTM

**Comment by TRohit20** [comment]
> LGTM

So you are gonna merge it? :)

**Review by Indira-kumar — COMMENTED** [review]
As a normal developer, I feel both the projects look beginner friendly, and has good amount of learning perks. So I would suggest the maintainer to merge this request at the earliest.

**Comment by TRohit20** [comment]
@Indira-kumar Thank you man. Yes, I even have comments and notes for the most part. Pre-processors can be learnt too.

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

**Pull request merged**
