### PR TITLE
Add Remote3 and UseWeb3

### PR DESCRIPTION
**Pull request by dhanushreddy291**
## Changes proposed
Add Remote3 and UseWeb3

## Note to reviewers
Adding Remote3 and UseWeb3

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
@dhanushreddy291 please fill in the pr template with the issue you are trying to solve please add `closes #issue-number`. Once done we will proceed towards review of your pr

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by SaptarshiSarkar12 — APPROVED** [review]
LGTM 👍 . 
@dhanushreddy291 Please fix the branch conflicts, then the changes can be merged.

**Comment by kaiwalyakoparkar** [comment]
@dhanushreddy291 can you please resolve the merge conflict

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by dhanushreddy291** [comment]
This PR is not referencing to any issue. I just added two new websites which I use. (Remote3 and UseWeb3)
I am confused what's causing the Branch Conflict?

**Comment by kaiwalyakoparkar** [comment]
@dhanushreddy291 if you click on the "Resolve Conflict" button then you will be able to see the conflicting code.

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
