### PR TITLE
Added 5 Mobile Projects

### PR DESCRIPTION
**Pull request by yash-gulatii**
Added 5 Mobile Projects to contribution list

- f8app : Source code of the official F8 app of 2017, powered by React Native and other Facebook open source projects.
- Fresco : An Android library for managing images and the memory they use.
- IGListKit : A data-driven UICollectionView framework for building fast and flexible lists.
- stetho : Stetho is a debug bridge for Android applications, enabling the powerful Chrome Developer Tools and much more.
- yoga : Yoga is a cross-platform layout engine which implements Flexbox.

### CODE REVIEW

**Comment by siddhant-khisty** [comment]
hey @yash-gulatii, please provide some info and details on these projects

**Comment by yash-gulatii** [comment]
Hey @siddhant-khisty, Is it okay now?

**Review by siddhant-khisty — APPROVED** [review]
LGTM
cc @kaiwalyakoparkar

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

**Comment by vmc111** [comment]
Hello I'm Interested in the Fresco Project. And want to contribute I'm an absolute beginner. Could anyone guide me to how to approach for contributing in the project.

**Pull request merged**
