### PR TITLE
Added android roadmap

### PR DESCRIPTION
**Pull request by c99SRS**
## Fixes Issue
#204 

## Changes proposed

Added roadmap for Android. Added necessary resources

## Note to reviewers

Please review it. Let me know if anything missing

### CODE REVIEW

**Comment by c99SRS** [comment]
Hi @siddhant-khisty please review my PR and merge it

**Comment by siddhant-khisty** [comment]
@c99SRS Please don't link to the website. The entire roadmap needs to be converted to a markdown format. Also please make new PRs for the other files that you have changed. Keep the scope of this PR focused on converting the roadmap.

**Comment by kaiwalyakoparkar** [comment]
@c99SRS please read the instructions provided in the issue. Every step is mentioned clearly. You can ask us if you find something difficult. I am closing this PR as a fresh new pr would be easier for both of us

**Comment by c99SRS** [comment]
yeah sure

**Comment by samvid2020** [comment]
hey can you assign this issue to me @kaiwalyakoparkar

**Pull request closed without merging**
