### PR TITLE
Added Projects to Blockchain Roadmap

### PR DESCRIPTION
**Pull request by dinesh11515**
Added projects to Blockchain Roadmap

### CODE REVIEW

**Review by siddhant-khisty — CHANGES_REQUESTED** [review]
Hey @dinesh11515, please arrange the projects alphabetically

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by dinesh11515** [comment]
Actually readme is not in alphabetically order

**Comment by cosmicqbit** [comment]
@dinesh11515 Thanks for the contribution. I think PR title can be changed to something relevant, like "Added Projects to Blockchain Roadmap"

**Comment by cosmicqbit** [comment]
> 

That could be done but it's not actually needed cuz having projects in alphabetical order ain't gonna help with anything, people can choose to contribute to any project they want.

**Comment by dinesh11515** [comment]
> @dinesh11515 Thanks for the contribution. I think PR title can be changed to something relevant, like "Added Projects to Blockchain Roadmap"

Changed..

**Comment by cosmicqbit** [comment]
@dinesh11515 I mean here: 
image

**Comment by dinesh11515** [comment]
> @dinesh11515 I mean here: 
> 
> image
> 
> 
Ok changed

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm, thank you so much for contributing

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
