### PR TITLE
Rearranged the list alphabetically

### PR DESCRIPTION
**Pull request by NitanJana**

### CODE REVIEW

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by NitanJana** [comment]
Thank you, should I do the same for all tech stacks?

**Comment by kaiwalyakoparkar** [comment]
@NitanJana contributions are always welcome but please open the issue if you are working on it first. This way it's easier for us to keep track :)

**Comment by NitanJana** [comment]
@kaiwalyakoparkar Alright thanks, I'm new to open source. Should I open new issue for the rearranging thing or push on the already opened issue?

**Comment by kaiwalyakoparkar** [comment]
@NitanJana create new issue for every tech stack you are rearranging and create separate pull requests for each one of them.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Pull request merged**
