### PR TITLE
Added an open source project

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
## Changes proposed
Added `Drifty`, an open source project.

### CODE REVIEW

**Comment by siddhant-khisty** [comment]
Hey @SaptarshiSarkar12, could you please provide a description about what the project does, what is it about, how can people contribute, etc?

The documentation of the project provides very little insight.

**Comment by SaptarshiSarkar12** [comment]
Ok @siddhant-khisty . I shall let you know after I have included the above points in the documentation.

**Comment by SaptarshiSarkar12** [comment]
@siddhant-khisty I have successfully made the documentation more insightful by adding the points that you have mentioned and have added some other points as well.

**Comment by SaptarshiSarkar12** [comment]
@siddhant-khisty Please re-review this PR.

**Comment by SaptarshiSarkar12** [comment]
@kaiwalyakoparkar Please review this PR.

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]
usage video is not rendering
Rending issue

**Comment by SaptarshiSarkar12** [comment]
@kaiwalyakoparkar Please check it again. I have fixed it.

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM

**Comment by SaptarshiSarkar12** [comment]
Thanks @kaiwalyakoparkar for reviewing this PR

**Pull request merged**
