### PR TITLE
Added roadmap for blockchain

### PR DESCRIPTION
**Pull request by c99SRS**
## Fixes Issue

#205

### CODE REVIEW

**Comment by c99SRS** [comment]
HI @siddhant-khisty please review my PR and merge it

**Comment by siddhant-khisty** [comment]
@c99SRS We are going to remove the roadmap which is on the website. Please don't link to the website. The roadmap needs to be converted to a markdown format which can be displayed here on GitHub.

**Comment by c99SRS** [comment]
HI @siddhant-khisty  removed the roadmap from the readme file. Please review it

**Comment by siddhant-khisty** [comment]
Please refer to #207 for how you have to make the PR

**Comment by kaiwalyakoparkar** [comment]
@c99SRS I think you didn't get the issue. Please refer the PR #207 to see how they have contributed to this issue. I am closing this PR

**Pull request closed without merging**
