### PR TITLE
Added PocketBase to Backend directory

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
## Changes proposed
Added a Backend project named PocketBase to the Backend directory.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@kaiwalyakoparkar Please review it.

**Review by siddhant-khisty — APPROVED** [review]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by SaptarshiSarkar12** [comment]
@kaiwalyakoparkar Please merge this PR.

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
