### PR TITLE
added more communities and OSS project

### LINKED ISSUE #146: Add Communities and OSS project on Blockchain
Communities like :
- 4C
- Polygon
- WebX DAO
- Moralis DAO

must be added to the list of communities to join.

Open Source Project [create-web3-dapp](https://github.com/Eversmile12/create-web3-dapp) by Vitto Rivabella should be added to the list of OSS projects.

### PR DESCRIPTION
**Pull request by chirag0002**
- Added 4 more Communities' names with their respective discord link to the list.

Preview README md - roadmaps - Visual Studio Code 24-08-2022 19_05_55 (2)

- Added an OSS project to the list and arranged them all in alphabetical order.

Preview README md - roadmaps - Visual Studio Code 24-08-2022 19_06_22 (2)

closes #146

### CODE REVIEW

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]

**Comment by kaiwalyakoparkar** [comment]
@chirag0002 can you please also resolve the merge conflict

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by chirag0002** [comment]
Ohk, looking for it.

**Comment by chirag0002** [comment]
Resolved the conflict errors, and removed extra lines. You can review it again @kaiwalyakoparkar.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm, thank you so much for contributing

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by chirag0002** [comment]
Very glad to know that my PR got merged...Thank You :)

**Pull request merged**
