### PR TITLE
Adding super-linter

### PR DESCRIPTION
**Pull request by vasucp1207**
- Currently, I see a lot of folks adding the **Roadmaps** readme to the project but they do not write the clean code. So here is the **super-linter** github action for reviewing the code quality.

### CODE REVIEW

**Comment by vasucp1207** [comment]
Hey, @kaiwalyakoparkar I think it works fine.
Screenshot 2022-10-20 at 10 28 04 PM


Screenshot 2022-10-20 at 10 42 44 PM

**Comment by siddhant-khisty** [comment]
cc: @kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@vasucp1207 just one more thing before we can merge this. Could you please add the rules to the contributing.md file. (So people can refer that if the linting is failing for them.)

**Comment by vasucp1207** [comment]
@kaiwalyakoparkar rules about following the code styling to passing the linting?

**Comment by siddhant-khisty** [comment]
That's right @vasucp1207

**Comment by vasucp1207** [comment]
@kaiwalyakoparkar, done.

**Review by siddhant-khisty — APPROVED** [review]
LGTM

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

**Pull request merged**
