### PR TITLE
added algebra-for-you

### PR DESCRIPTION
**Pull request by razaahmad333**

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
@razaahmad333 please resolve the merge conflict

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm, thanks for contributing. Please resolve the merge conflict so that we can merge it

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Comment by kaiwalyakoparkar** [comment]
Hey @razaahmad333 do you need any help resolving the conflict?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by razaahmad333** [comment]
> Hey @razaahmad333 do you need any help resolving the conflict?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question

Hey sorry for the delay,
I have resolved the conflicts

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
