### PR TITLE
GSoC All Front end Projects

### PR DESCRIPTION
**Pull request by sanjayk0508**
This particular github repo has all GSoc projects for front end

### CODE REVIEW

**Review by vish-han — COMMENTED** [review]
Its Working Fine, This PR can be Approved.

**Review by vish-han — APPROVED** [review]

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
Since we do not have control over how that repo will change, please add individual projects in the README file.

**Comment by sanjayk0508** [comment]
Ok, got it. There are almost 100 Projects & 50 Organizations of GSoC in this particular repo.
I will add all the projects & organizations individually with links in the README file.

**Comment by sanjayk0508** [comment]
ADDED👍

**Comment by sanjayk0508** [comment]
ok understood, will do it

**Comment by sanjayk0508** [comment]
Added the repos in alphabetical order & removed the header, description and texts.
Had to copy all the repos (pervious + new ones) in excel in order to align them in alphabetical order. Didn't disturb any of the previous repos.
Also double checked the Names & Links

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm, thank you so much for contributing

**Pull request merged**
